name: Auto Create Pull Request
on:
  push:
    branches:
      - 'feature'
  

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "feature"
          destination_branch: "main"
          pr_title: "PR: รวมงานจากเครื่องของคุณ"
          pr_body: "สร้างอัตโนมัติจาก GitHub Action"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  deploy_job:                            # (1) Job ID
    name: Deploy to Sandbox
    needs: create-pull-request           # (5) Needs: ต้องรอให้ Job 'build_job' สำเร็จก่อน
    if: github.ref == 'refs/heads/main'  # (5) Conditions: ทำเฉพาะเมื่ออยู่บน branch main
    runs-on: windows-latest              # (2) Runs-on
    environment: BusinessCentral-Sandbox # (4) Environment (ระบุสภาพแวดล้อมที่ใช้)
    steps:                               # (3) Steps
      - name: Deploy App to BC
        run: |                           # (3.2) Run: เขียนคำสั่งเอง
          echo "Connecting to Sandbox..."
          echo "Deploying .app file from build artifacts..."
        shell: powershell
